### ISSUE TITLE
Protected in interfaces

### ISSUE THREAD

**Issue by luaks** [bicoom/oom#36]
When defining an Interface, you cannot define encapsulation for your methods.
Is there a way, to enforce encapsulation, so only classes implemented via the interface can use this function?

**Comment by bicoom** [comment]
One of the better explanations I found is:
"An interface by definition is a contract between a caller and an object, not between a class and its subclasses." [http://stackoverflow.com/questions/516148/why-cant-i-have-protected-interface-members] 

If you see it this way, it makes sense to only allow publicly visible operations in interfaces, since encapsulation/protected/private are basically implementation details, which by definition cannot be visible from the outside (from a caller's perspective).

If you want to ensure, that all implementors (subclasses) implement a certain protected method, then an (abstract) base class can be used, which can be seen as "a contract between a base class and it's subclasses)".

See also [https://msdn.microsoft.com/library/ms173156.aspx] for language specification.

**Comment by bicoom** [comment]
linked issue to https://github.com/bicoom/oom/wiki/FAQ
