### ISSUE TITLE
add walkthrough for TortoiseGit

### ISSUE THREAD

**Issue by stefanmaierhofer** [bicoom/oom#4]
similar to walkthrough for command line git (git-scm)

**Comment by mriedmann** [comment]
maybe you could consider the VS2015 build-in Git support (https://msdn.microsoft.com/en-us/library/hh850445.aspx), instead of tortoisegit. If a standalone GUI solution is needed, git-scm also offers a GUI. If this is not enought, SmartGit (http://www.syntevo.com/smartgit/) is a free, MultiOS alternative to TortoiseGit (which is only available for Windows).

**Comment by stefanmaierhofer** [comment]
Thanks!

Added references to various optional git clients to https://github.com/bicoom/oom/wiki/Git.
Removed reference to TortoiseGit from T1.2.
